import 'package:smart_device_dart/features/smart_device/application/usecases/devices_pin_configuration_u/device_configuration_base_class.dart';
import 'package:smart_device_dart/features/smart_device/application/usecases/devices_pin_configuration_u/pin_information.dart';

/// Configuration for the NanoPi NEO Air
class NanoPiNEOAirConfiguration extends DeviceConfigurationBaseClass {
  /// Setting the configuration by PinInformation list
  NanoPiNEOAirConfiguration() {
    pinList = _pinListNanoPiNEOAir;
  }

  static final List<PinInformation> _pinListNanoPiNEOAir = <PinInformation>[
    /// GPIO Pin Description
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 1,
      index: 1,
      gpioColumn: 1,
      name: 'SYS_3.3V',
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 2,
      index: 2,
      gpioColumn: 2,
      name: 'VDD_5V',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 3,
      index: 3,
      gpioColumn: 1,
      gpioValue: 'GPIOA12',
      name: 'I2C0_SDA/GPIOA12 ',
      wPi: 8,
      bcmOrLinuxGpio: 12,
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 4,
      index: 4,
      gpioColumn: 2,
      name: 'VDD_5V',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 5,
      index: 5,
      gpioColumn: 1,
      gpioValue: 'GPIOA11',
      name: 'I2C0_SCL/GPIOA11',
      wPi: 9,
      bcmOrLinuxGpio: 11,
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 6,
      index: 6,
      gpioColumn: 2,
      name: 'GND',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 7,
      index: 7,
      gpioColumn: 1,
      gpioValue: 'GPIOG11',
      name: 'GPIOG11',
      wPi: 7,
      bcmOrLinuxGpio: 203,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 8,
      index: 8,
      gpioColumn: 2,
      gpioValue: 'GPIOG6',
      name: 'UART1_TX/GPIOG6',
      wPi: 15,
      bcmOrLinuxGpio: 198,
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 9,
      index: 9,
      gpioColumn: 1,
      name: 'GND',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 10,
      index: 10,
      gpioColumn: 2,
      gpioValue: 'GPIOG7',
      name: 'UART1_RX/GPIOG7',
      wPi: 16,
      bcmOrLinuxGpio: 199,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 11,
      index: 11,
      gpioColumn: 1,
      gpioValue: 'GPIOA0',
      name: 'UART2_TX/GPIOA0',
      wPi: 0,
      bcmOrLinuxGpio: 0,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 12,
      index: 12,
      gpioColumn: 2,
      gpioValue: 'GPIOA6',
      name: 'GPIOA6',
      wPi: 1,
      bcmOrLinuxGpio: 6,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 13,
      index: 13,
      gpioColumn: 1,
      gpioValue: 'GPIOA2',
      name: 'UART2_RTS/GPIOA2',
      wPi: 2,
      bcmOrLinuxGpio: 2,
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 14,
      index: 14,
      gpioColumn: 2,
      name: 'GND',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 15,
      index: 15,
      gpioColumn: 1,
      gpioValue: 'GPIOA3',
      name: 'UART2_CTS/GPIOA3',
      wPi: 3,
      bcmOrLinuxGpio: 3,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 16,
      index: 16,
      gpioColumn: 2,
      gpioValue: 'GPIOG8',
      name: 'UART1_RTS/GPIOG8',
      wPi: 4,
      bcmOrLinuxGpio: 200,
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 17,
      index: 17,
      gpioColumn: 1,
      name: 'SYS_3.3V',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 18,
      index: 18,
      gpioColumn: 2,
      gpioValue: 'GPIOG9',
      name: 'UART1_CTS/GPIOG9',
      wPi: 5,
      bcmOrLinuxGpio: 201,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 19,
      index: 19,
      gpioColumn: 1,
      gpioValue: 'GPIOC0',
      name: 'SPI0_MOSI/GPIOC0',
      wPi: 12,
      bcmOrLinuxGpio: 64,
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 20,
      index: 20,
      gpioColumn: 2,
      name: 'GND',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 21,
      index: 21,
      gpioColumn: 1,
      gpioValue: 'GPIOC1',
      name: 'SPI0_MISO/GPIOC1',
      wPi: 13,
      bcmOrLinuxGpio: 65,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 22,
      index: 22,
      gpioColumn: 2,
      gpioValue: 'GPIOA1',
      name: 'UART2_RX/GPIOA1',
      wPi: 6,
      bcmOrLinuxGpio: 1,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 23,
      index: 23,
      gpioColumn: 1,
      gpioValue: 'GPIOC2',
      name: 'SPI0_CLK/GPIOC2',
      wPi: 14,
      bcmOrLinuxGpio: 66,
    ),
    PinInformation(
      category: 'CPIO',
      pinAndPhysicalPinConfiguration: 24,
      index: 24,
      gpioColumn: 2,
      gpioValue: 'GPIOC3',
      name: 'SPI0_CS/GPIOC3',
      wPi: 10,
      bcmOrLinuxGpio: 67,
    ),

    /// USB/I2S/IR Pin Description
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 25,
      index: 1,
      gpioColumn: 3,
      name: 'VDD_5V',
      description: '5V Power Out',
    ),
    PinInformation(
      category: 'USB',
      pinAndPhysicalPinConfiguration: 26,
      index: 2,
      gpioColumn: 3,
      name: 'USB-DP2',
      description: 'USB2 DP Signal',
    ),
    PinInformation(
      category: 'USB',
      pinAndPhysicalPinConfiguration: 27,
      index: 3,
      gpioColumn: 3,
      name: 'USB-DM2',
      description: ' USB2 DM Signal',
    ),
    PinInformation(
      category: 'USB',
      pinAndPhysicalPinConfiguration: 28,
      index: 4,
      gpioColumn: 3,
      name: 'USB-DP3',
      description: 'USB3 DP Signal',
    ),
    PinInformation(
      category: 'USB',
      pinAndPhysicalPinConfiguration: 29,
      index: 5,
      gpioColumn: 3,
      name: 'USB-DM3',
      description: 'USB3 DM Signal',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 30,
      index: 6,
      gpioColumn: 3,
      gpioValue: 'GPIOL11',
      name: 'GPIOL11/IR-RX',
      description: 'GPIOL11 or IR Receive',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 31,
      index: 7,
      gpioColumn: 3,
      gpioValue: 'GPIOA17',
      name: 'SPDIF-OUT/GPIOA17',
      wPi: 19,
      bcmOrLinuxGpio: 17,
      description: 'GPIOA17 or SPDIF-OUT',
    ),
    PinInformation(
      category: 'USB/Audio/IR',
      pinAndPhysicalPinConfiguration: 32,
      index: 8,
      gpioColumn: 3,
      name: 'PCM0_SYNC/I2S0_LRC',
      description: 'I2S/PCM Sample Rate Clock/Sync',
    ),
    PinInformation(
      category: 'USB/Audio/IR',
      pinAndPhysicalPinConfiguration: 33,
      index: 9,
      gpioColumn: 3,
      name: 'PCM0_CLK/I2S0_BCK',
      description: 'I2S/PCM Sample Rate Clock',
    ),
    PinInformation(
      category: 'USB/Audio/IR',
      pinAndPhysicalPinConfiguration: 34,
      index: 10,
      gpioColumn: 3,
      name: 'PCM0_DOUT/I2S0_SDOUT',
      description: 'I2S/PCM Serial Bata Output',
    ),
    PinInformation(
      category: 'USB/Audio/IR',
      pinAndPhysicalPinConfiguration: 35,
      index: 11,
      gpioColumn: 3,
      name: 'PCM0_DIN/I2S0_SDIN',
      description: 'I2S/PCM Serial Data Input',
    ),
    PinInformation(
      category: 'Power',
      pinAndPhysicalPinConfiguration: 36,
      index: 12,
      gpioColumn: 3,
      name: 'GND',
      description: '0V',
    ),

    /// Debug Port（UART0）
    PinInformation(
      category: 'Power',
      index: 1,
      gpioColumn: 4,
      name: 'GND',
    ),
    PinInformation(
      category: 'Power',
      index: 2,
      gpioColumn: 4,
      name: 'VDD_5V',
      description: '0V',
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 37,
      index: 3,
      gpioColumn: 4,
      gpioValue: 'GPIOA4',
      name: 'UART_TXD0/GPIOA4',
      wPi: 17,
      bcmOrLinuxGpio: 4,
    ),
    PinInformation(
      category: 'GPIO',
      pinAndPhysicalPinConfiguration: 38,
      index: 4,
      gpioColumn: 4,
      gpioValue: 'GPIOA5',
      name: 'UART_RXD0/GPIOA5/PWM0',
      wPi: 18,
      bcmOrLinuxGpio: 5,
    ),

    ///  Audio Port
    PinInformation(
      category: 'Audio',
      index: 1,
      name: 'LL',
      description: 'LINEOUTL, LINE-OUT Left Channel Output',
    ),
    PinInformation(
      category: 'Audio',
      index: 2,
      name: 'LR',
      description: 'LINEOUTR, LINE-OUT Right Channel Output',
    ),
    PinInformation(
      category: 'Audio',
      index: 3,
      name: 'MICN',
      description: 'MICIN1N, Microphone Negative Input',
    ),
    PinInformation(
      category: 'Audio',
      index: 4,
      name: 'MICP',
      description: 'MICIN1P, Microphone Positive Input',
    ),

    /// DVP Camera IF Pin Spec
    PinInformation(
      category: 'Power',
      index: 1,
      name: 'SYS_3.3V',
      description: '3.3V power output, to camera modules',
    ),
    PinInformation(
      category: 'Power',
      index: 2,
      name: 'SYS_3.3V',
      description: '3.3V power output, to camera modules',
    ),
    PinInformation(
      category: 'I2C',
      index: 3,
      name: 'I2C2_SCL',
      description: 'I2C Clock Signal',
    ),
    PinInformation(
      category: 'I2C',
      index: 4,
      name: 'I2C2_SDA',
      description: 'I2C Data Signal',
    ),
    PinInformation(
      category: 'GPIO',
      index: 5,
      gpioValue: 'GPIOE15',
      name: 'GPIOE15',
      description: 'Regular GPIO, control signals output to camera modules',
    ),
    PinInformation(
      category: 'GPIO',
      index: 6,
      gpioValue: 'GPIOE14',
      name: 'GPIOE14',
      description: 'Regular GPIO, control signals output to camera modules',
    ),
    PinInformation(
      category: 'Power',
      index: 7,
      name: 'GND',
      description: 'Gound, 0V',
    ),
    PinInformation(
      category: 'MCLK',
      index: 8,
      name: 'MCLK',
      description: 'Clock signals output to camera modules',
    ),
    PinInformation(
      category: 'Power',
      index: 9,
      name: 'GND',
      description: 'Gound, 0V',
    ),
    PinInformation(
      category: 'NC',
      index: 10,
      name: 'NC',
      description: 'Not Connected',
    ),
    PinInformation(
      category: 'VSYNC',
      index: 11,
      name: 'VSYNC',
      description: 'vertical synchronization to CPU　from camera modules',
    ),
    PinInformation(
      category: 'HREF/HSYNC',
      index: 12,
      name: 'HREF/HSYNC',
      description: 'HREF/HSYNC signal to CPU from camera modules',
    ),
    PinInformation(
      category: 'Power',
      index: 13,
      name: 'GND',
      description: 'Gound, 0V',
    ),
    PinInformation(
      category: 'PCLK',
      index: 14,
      name: 'PCLK',
      description: 'PCLK signal to CPU from camera modules',
    ),
    PinInformation(
      category: 'Power',
      index: 15,
      name: 'GND',
      description: 'Gound, 0V',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 16,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 17,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 18,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 19,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 20,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 21,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 22,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Data bit7-0',
      index: 23,
      name: 'Data bit7-0',
      description: 'data signals',
    ),
    PinInformation(
      category: 'Power',
      index: 24,
      name: 'GND',
      description: 'Gound, 0V',
    ),
  ];

  @override
  PinInformation getNextFreeGpioPin({List<PinInformation> ignorePinsList}) =>
      getNextFreeGpioPinHelper(pinList, ignorePinsList: ignorePinsList);
}
